"""create study targets table

Revision ID: 0673add432f4
Revises: 14f6398ed468
Create Date: 2026-05-26 21:03:53.027987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0673add432f4'
down_revision: Union[str, Sequence[str], None] = '14f6398ed468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_targets',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID，关联 users.id'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='目标名称，例如数据库系统期末复习'),
    sa.Column('subject', sa.String(length=100), nullable=True, comment='课程或考试科目名称'),
    sa.Column('target_type', sa.Enum('course', 'exam', name='study_target_type'), nullable=False, comment='目标类型，course 表示课程目标，exam 表示考试目标'),
    sa.Column('exam_date', sa.Date(), nullable=True, comment='考试日期，可为空'),
    sa.Column('review_goal', sa.Text(), nullable=True, comment='复习目标，例如掌握重点章节并完成错题复盘'),
    sa.Column('description', sa.Text(), nullable=True, comment='目标备注说明，可为空'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记，True 表示该目标已删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间，由数据库生成'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间，由 SQLAlchemy 在更新时刷新'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_targets_id'), 'study_targets', ['id'], unique=False)
    op.create_index(op.f('ix_study_targets_user_id'), 'study_targets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_targets_user_id'), table_name='study_targets')
    op.drop_index(op.f('ix_study_targets_id'), table_name='study_targets')
    op.drop_table('study_targets')

    sa.Enum("course", "exam", name="study_target_type").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
