"""create materials table

Revision ID: 14de6dec0d7c
Revises: 0673add432f4
Create Date: 2026-05-26 21:43:24.826498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14de6dec0d7c'
down_revision: Union[str, Sequence[str], None] = '0673add432f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False, comment='自增主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='所属用户ID，关联 users.id'),
    sa.Column('target_id', sa.Integer(), nullable=False, comment='所属课程/考试目标ID，关联 study_targets.id'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='用户上传时的原始文件名'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='服务端保存时生成的唯一文件名'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='服务端文件存储路径'),
    sa.Column('file_type', sa.Enum('pdf', 'txt', 'image', name='material_type'), nullable=False, comment='资料文件类型，支持 pdf、txt、image'),
    sa.Column('content_type', sa.String(length=100), nullable=True, comment='上传文件的 MIME 类型'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='文件大小，单位字节'),
    sa.Column('parse_status', sa.Enum('uploaded', 'parsing', 'parsed', 'failed', name='material_parse_status'), nullable=False, comment='资料解析状态'),
    sa.Column('parsed_text', sa.Text(), nullable=True, comment='资料解析后的文本内容'),
    sa.Column('parse_error', sa.Text(), nullable=True, comment='资料解析失败原因'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='软删除标记，True 表示该资料已删除'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录创建时间，由数据库生成'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='记录最后更新时间，由 SQLAlchemy 在更新时刷新'),
    sa.ForeignKeyConstraint(['target_id'], ['study_targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_materials_id'), 'materials', ['id'], unique=False)
    op.create_index(op.f('ix_materials_parse_status'), 'materials', ['parse_status'], unique=False)
    op.create_index(op.f('ix_materials_target_id'), 'materials', ['target_id'], unique=False)
    op.create_index(op.f('ix_materials_user_id'), 'materials', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_materials_user_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_target_id'), table_name='materials')
    op.drop_index(op.f('ix_materials_parse_status'), table_name='materials')
    op.drop_index(op.f('ix_materials_id'), table_name='materials')
    op.drop_table('materials')

    sa.Enum("pdf", "txt", "image", name="material_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum("uploaded", "parsing", "parsed", "failed", name="material_parse_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
